### ISSUE TITLE
Students installation

### ISSUE THREAD

**Issue by GeraldineDerroire** [sylvainschmitt/Seminario_LoggingLab#2]
- [x] Prepare tuto written for students to install the enviro before the workshop
- [x] Test with guinea pigs
- [ ] _Prepare tuto video for students to install the enviro before the workshop_

**Comment by sylvainschmitt** [comment]
> Prepare tuto (written or video) for students to install the enviro before the workshop.

I would use both a GitHub wiki (https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) and a youtube video.

**Comment by GeraldineDerroire** [comment]
regarding renv, when I clone the project and first open it, I get that ![Image](https://github.com/user-attachments/assets/6caf3694-5728-42c6-8284-fb60a2c7abd5)
But I'm not asked if I want to use renv::restore, as it should according to that : https://rstudio.github.io/renv/articles/renv.html#collaboration

**Comment by GeraldineDerroire** [comment]
> regarding renv, when I clone the project and first open it, I get that ![Image](https://github.com/user-attachments/assets/6caf3694-5728-42c6-8284-fb60a2c7abd5) But I'm not asked if I want to use renv::restore, as it should according to that : https://rstudio.github.io/renv/articles/renv.html#collaboration

also, when I did renv::restore, it did apparently not installed tidyverse, as I had to manually install it afterwards.

**Comment by sylvainschmitt** [comment]
Ok I'll wait for the review to not mess up to much the repo but that's not normal. I may have not updated renv lockfile on my side.

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , I prepared a wiki for the students installation here: https://github.com/sylvainschmitt/Seminario_LoggingLab/wiki/Instala%C3%A7%C3%A3o . Could you review it? I suggest first to share it with Plinio and Lucas for a test. And after the test we may ask one of them or any other Portuguese speaker to make a video following the steps?

**Comment by sylvainschmitt** [comment]
PS: we should extend the README of the repo accordingly.

**Comment by GeraldineDerroire** [comment]
> [@GeraldineDerroire](https://github.com/GeraldineDerroire) , I prepared a wiki for the students installation here: https://github.com/sylvainschmitt/Seminario_LoggingLab/wiki/Instala%C3%A7%C3%A3o . Could you review it? I suggest first to share it with Plinio and Lucas for a test. And after the test we may ask one of them or any other Portuguese speaker to make a video following the steps?

I've reviewed it. It's my first time using a wiki and I wanted to finish today, so I went for the easy solution to comment in the text using  . You can do a search with <!-- to see all my comments. 

Ideally, we would need to test it on a computer without R and anything... But may be hard to find...

Oh and regarding the renv, I didn't update the renv... should I have ? Should I do it everytime?
