### ISSUE TITLE
Practioners pres

### ISSUE THREAD

**Issue by GeraldineDerroire** [sylvainschmitt/Seminario_LoggingLab#4]
- [x] Dev skeleton pres LoggingLab for practioners
- [x] @sylvainschmitt review
- [x] Fill the skeleton
- [ ] Validate the content and Portuguese (@sylvainschmitt , Plinio & Lucas?)

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , where can I find the skeleton to review it?

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , I'm reorganizing a bit the issues but we may discuss it.

**Comment by GeraldineDerroire** [comment]
> [@GeraldineDerroire](https://github.com/GeraldineDerroire) , where can I find the skeleton to review it?

In the equipe on Teams, in the fichier tab.

**Comment by GeraldineDerroire** [comment]
> [@GeraldineDerroire](https://github.com/GeraldineDerroire) , I'm reorganizing a bit the issues but we may discuss it.

fine for me !

**Comment by sylvainschmitt** [comment]
> > [@GeraldineDerroire](https://github.com/GeraldineDerroire) , where can I find the skeleton to review it?
> 
> In the equipe on Teams, in the fichier tab.

@GeraldineDerroire , I just reviewed and only added two comments. This good for me, you can start filling the skeleton. However, as an intermediary step you could also list the figures needed, and I could prepare a qmd to prepare them with reproducible code in this repository.

**Comment by GeraldineDerroire** [comment]
> > > [@GeraldineDerroire](https://github.com/GeraldineDerroire) , where can I find the skeleton to review it?
> > 
> > 
> > In the equipe on Teams, in the fichier tab.
> 
> [@GeraldineDerroire](https://github.com/GeraldineDerroire) , I just reviewed and only added two comments. This good for me, you can start filling the skeleton. However, as an intermediary step you could also list the figures needed, and I could prepare a qmd to prepare them with reproducible code in this repository

**Comment by GeraldineDerroire** [comment]
humm... I may have closed the issue by mistake... should be reopen now...

**Comment by sylvainschmitt** [comment]
A quick note regarding your first figure. Dividing the CirCorr doesn't adjust point sizes. You should adjust the scale for that, i.e.:
```
scale_size_continuous(range = c(.25, 3))
```
In py next push I'll update the first inventory figure closed to your figures but with this adjusted scale for exemple.

**Comment by GeraldineDerroire** [comment]
> A quick note regarding your first figure. Dividing the CirCorr doesn't adjust point sizes. You should adjust the scale for that, i.e.:
> 
> ```
> scale_size_continuous(range = c(.25, 3))
> ```
> 
> In py next push I'll update the first inventory figure closed to your figures but with this adjusted scale for exemple.

indeed, thanks!

**Comment by GeraldineDerroire** [comment]
I close this issue as I don't think we will get feedback on it now.
