### ISSUE TITLE
Students pres

### ISSUE THREAD

**Issue by GeraldineDerroire** [sylvainschmitt/Seminario_LoggingLab#5]
- [x] Dev skeleton pres LoggingLab
- [x] @GeraldineDerroire 1st review
- [x] Fill the skeleton 
- [x] Geraldine 2nd review
- [x] @sylvainschmitt  see what you keep from G's 2nd review
- [ ] Plinio & Lucas test with Pt review

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , could you review the pres skeleton here: https://sylvainschmitt.github.io/Seminario_LoggingLab? Sorry there is a lot of content already, but please focus mainly on the structure.

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , if you didn't already start, I advise you use the review system of pull request with https://github.com/sylvainschmitt/Seminario_LoggingLab/pull/8 . It will ease a line by line review. You can find help here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews .

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire , the first full version is ready. Could you review it? Next I'll prepare the installation tutorial for Plinio & Lucas and I'll ask them to test & review the Portuguese. By the way I updated renv lock which was lacking indeed a lot of packages including LoggingLab!

**Comment by GeraldineDerroire** [comment]
- maybe harmonise the phrasing (eg: sometimes corte seletivo, sometimes extração seletiva..) ? But it may be better to wait for Lucas and Plinio's feedback on the language
- the chalkboard and notes is a super cool addition, do you know how to save them if needed?

**Comment by GeraldineDerroire** [comment]
@sylvainschmitt I've now made the pull request. 
But what are all thoses files created in index_files/libs? I had a very hard time to stage all of that, with my computer freezing and all... Are the due to the chalkboard plugging?

**Comment by sylvainschmitt** [comment]
> maybe harmonise the phrasing (eg: sometimes corte seletivo, sometimes extração seletiva..) ? But it may be better to wait for Lucas and Plinio's feedback on the language

Ok, I didn't checked that one.

> the chalkboard and notes is a super cool addition, do you know how to save them if needed?

Yes we can, but with the mouse it is not easy to really write/draw. Anyhow, we can export the drawing at the end (you just need to avoid reloading the pres).

>  when I click on the arrow on slide 17 to go to the next slides, it goes to slide 24, and I couldn't figure out why...

Yes this is because you are going down and up for slides within chapters and the right and left are configured to switch chapters. You can see it with overview (touch o). But we can remove it I think.

>  there is a few points to discuss on how far/complicated we want to go/be. For exemple, do we talk about agregative species ? do we talk about allowing "forced diversification" (specieslax) ? let's be consistent for the presentation to practitionners

Indeed, I already removed a lot. I don't know for practitioners but for students I wanted to be the simplest because I imagined it as an intro to the package. So I'll say we drop aggregative and diversification, especially because I think it's really "Guyanese". What about directional felling?

**Comment by sylvainschmitt** [comment]
> @sylvainschmitt I've now made the pull request #9 . But what are all thoses files created in index_files/libs? I had a very hard time to stage all of that, with my computer freezing and all... Are the due to the chalkboard plugging?

This is great that you made a PR, I found the review system super useful. Here I don't think we'll interact much as I mainly agree but this can super useful in the future.

**Comment by GeraldineDerroire** [comment]
@sylvainschmitt : a small comment, on the slide of Quantificar de volumes, you get a volume of 93m3 so it would be worth saying that this is for the entire plot (as otherwise it is surprising that we are not back to 30m3). To get a volume/ha, we need to divide it by the area of the harvestable zone (and not by the area of the full plot).

**Comment by GeraldineDerroire** [comment]
another comment related to the one just before, you have used objectivelax = TRUE, which means that if you don't have enough to log at 30m3, you will log anyway. So maybe we actually log at less than 30m3 without knowing it... I will test it with objectivelax = FALSE, and I let you know if this is the case. If it is, I suggest logging at 20m3.
Or maybe do 20m3 anyway, as it is closer to actual practices I think ?

**Comment by GeraldineDerroire** [comment]
it works with objecttive = 30 m3. Do we keep it like this or change for 20?

**Comment by GeraldineDerroire** [comment]
> it works with objecttive = 30 m3. Do we keep it like this or change for 20?

sorry for the multiple message. It does run for 30m3 but only with diversification, but not if we don't do diversification... As I would like to present all the comparisons for the slides to practitionners around a pivot scenario (the first one in the table below), it would be good to run the pivot with 20m3, and set them all (but the one for which we manipulate the volume) to 20m3
![Image](https://github.com/user-attachments/assets/9cf825b3-a8f4-4291-95ef-408d4eefeb73)

Is it ok for you?

**Comment by sylvainschmitt** [comment]
Ok I'm switching to objective = 20, fuel = "0", winching = "2", directionfelling = "2", and diversification = TRUE as my new default scenario in the student presentation. It means that by default specieslax and objectivelax are FALSE but don't appear anymore in the call of functions to reduce things to discuss with students. It will be in my next push.

**Comment by GeraldineDerroire** [comment]
@sylvainschmitt on slide 39, it's not volume but biomass

**Comment by sylvainschmitt** [comment]
> @sylvainschmitt on slide 39, it's not volume but biomass

Fixed.

**Comment by GeraldineDerroire** [comment]
@sylvainschmitt do you understand what is going on with the trails here ?!
![Image](https://github.com/user-attachments/assets/6b918f9d-1b56-4336-9354-a1f8e8ff606e)

**Comment by GeraldineDerroire** [comment]
I close this issue as I don't think we will get feedback now
