### ISSUE TITLE
Notes during pres

### ISSUE THREAD

**Issue by GeraldineDerroire** [sylvainschmitt/Seminario_LoggingLab#6]
As we are going to be overwelmed by the presentation in portuguese, we need to identify a reliable way to take notes 
- one of us present and the other takes notes ? 
- we record everything?
- for the presentation with the practiionners, we take notes on the powerpoint itself as a way to reach an agreement ? if we do this, insert blank slides in the powerpoint

**Comment by sylvainschmitt** [comment]
> one of us present and the other takes notes ?

I'm not in favour of this option.

**Comment by sylvainschmitt** [comment]
> we record everything?

Possible but it means a lot of work to listen it again and take notes, but why not.

**Comment by sylvainschmitt** [comment]
> for the presentation with the practiionners, we take notes on the powerpoint itself as a way to reach an agreement ? if we do this, insert blank slides in the powerpoint

Seems good but maybe a bit non functional at the same time..

**Comment by GeraldineDerroire** [comment]
> > for the presentation with the practiionners, we take notes on the powerpoint itself as a way to reach an agreement ? if we do this, insert blank slides in the powerpoint
> 
> Seems good but maybe a bit non functional at the same time..

I'd be keen to try this one: in Santarem, we will have a lot of discussion time so we can readjust if it's not working well. ok ?

**Comment by sylvainschmitt** [comment]
Can we close the issue thus?
